// data.js
const data = {
  HTML: [
    {
      question: "What does HTML stand for?",
      options1: "HyperText Markup Language",
      options2: "Home Tool Markup Language",
      options3: "Hyperlinks and Text Markup Language",
      options4: "Hyperlinking Text Management Language",
      answer: 1,
    },
    {
      question: "Which HTML tag is used to create a hyperlink?",
      options1: "<link>",
      options2: "<a>",
      options3: "<href>",
      options4: "<hyperlink>",
      answer: 2,
    },
   {
      question: "Which HTML element is used to insert a line break?",
      options1: "<break>",
      options2: "<lb>",
      options3: "<br>",
      options4: "<line>",
      answer: 3,
    },
    {
      question: "What is the correct HTML tag for inserting an image?",
      options1: "<img href='image.jpg'>",
      options2: "<image src='image.jpg'>",
      options3: "<img src='image.jpg'>",
      options4: "<pic src='image.jpg'>",
      answer: 3,
    },
    {
      question: "Which tag is used to define the most important heading?",
      options1: "<heading>",
      options2: "<h6>",
      options3: "<h1>",
      options4: "<head>",
      answer: 3,
    },
    {
      question: "How can you make a numbered list in HTML?",
      options1: "<ul>",
      options2: "<ol>",
      options3: "<list>",
      options4: "<dl>",
      answer: 2,
    },
    {
      question: "Which HTML attribute is used to define inline styles?",
      options1: "font",
      options2: "style",
      options3: "class",
      options4: "styles",
      answer: 2,
    },
    {
      question: "Which tag is used to create a table row in HTML?",
      options1: "<table>",
      options2: "<td>",
      options3: "<tr>",
      options4: "<th>",
      answer: 3,
    },
    {
      question: "How do you add a comment in HTML?",
      options1: "// This is a comment",
      options2: "# This is a comment",
      options3: "/* This is a comment */",
      options4: "<!-- This is a comment -->",
      answer: 4,
    },
    {
      question: "Which HTML element is used for the largest heading?",
      options1: "<heading>",
      options2: "<h6>",
      options3: "<head>",
      options4: "<h1>",
      answer: 4,
   }
  ],
  CSS: [
    {
      question: "Which symbol is used to apply styles to a class in CSS?",
      options1: "#",
      options2: ".",
      options3: "*",
      options4: "@",
      answer: 2,
    },
    {
      question: "How do you change the text color in CSS?",
      options1: "font-color",
      options2: "color",
      options3: "text-style",
      options4: "background-color",
      answer: 2,
    },
    {
      question: "What is the correct CSS syntax to select all <p> elements?",
      options1: "p {}",
      options2: "#p {}",
      options3: ".p {}",
      options4: "<p> {}",
      answer: 1,
    },
    {
      question: "Which file extension is used for CSS files?",
      options1: ".html",
      options2: ".js",
      options3: ".css",
      options4: ".style",
      answer: 3,
   },
   {
      question: "Where should you link an external CSS file in HTML?",
      options1: "In the body tag",
      options2: "Before the DOCTYPE",
      options3: "Inside the <head> tag",
      options4: "After </html>",
      answer: 3,
    },
    {
      question: "Which property is used to center text?",
      options1: "text-style",
      options2: "text-align",
      options3: "font-align",
      options4: "center",
      answer: 2,
    },
    {
      question: "What is the default position value of HTML elements?",
      options1: "absolute",
      options2: "relative",
      options3: "static",
      options4: "fixed",
      answer: 3,
    },
    {
      question: "Which property is used to add space inside an element’s border?",
      options1: "margin",
      options2: "padding",
      options3: "spacing",
      options4: "border-spacing",
      answer: 2,
    },
    {
      question: "How do you make text bold using CSS?",
      options1: "font-bold",
      options2: "font-style: bold",
      options3: "font-weight: bold",
      options4: "text-decoration: bold",
      answer: 3,
    },
    {
      question: "Which CSS property is used to change the font of text?",
      options1: "font-style",
      options2: "font-family",
      options3: "text-font",
      options4: "font-weight",
      answer: 2,
    },
  ],
  JavaScript: [
    {
      question: "Which keyword is used to declare a variable in JavaScript?",
      options1: "let",
      options2: "define",
      options3: "varname",
      options4: "set",
      answer: 1,
    },
    {
      question: "What is the correct syntax to log something to the console?",
      options1: "log.console()",
      options2: "print()",
      options3: "console.log()",
      options4: "log()",
      answer: 3,
    },
    {
      question: "Which symbol is used for single-line comments in JavaScript?",
      options1: "//",
      options2: "/* */",
      options3: "<!-- -->",
      options4: "**",
      answer: 1,
    },
    {
      question: "How do you write a string in JavaScript?",
      options1: 'Inside parentheses',
      options2: 'Inside {}',
      options3: 'Inside quotes',
      options4: 'Inside square brackets',
      answer: 3,
    },
    {
      question: "What will `typeof 42` return?",
      options1: "string",
      options2: "number",
      options3: "boolean",
      options4: "object",
      answer: 2,
    },
    {
      question: "Which of the following is a boolean value?",
      options1: "yes",
      options2: "0",
      options3: "true",
      options4: "'false'",
      answer: 3,
    },
    {
      question: "Which operator is used for assignment?",
      options1: "=",
      options2: "==",
      options3: "===",
      options4: ":=",
      answer: 1,
    },
    {
      question: "Which function pops up a message box in the browser?",
      options1: "popup()",
      options2: "msg()",
      options3: "prompt()",
      options4: "alert()",
      answer: 4,
    },
    {
      question: "What does `NaN` stand for?",
      options1: "No assigned number",
      options2: "Not a Null",
      options3: "Not a Number",
      options4: "Negative and Null",
      answer: 3,
    },
    {
      question: "Which data type holds multiple values in a single variable?",
      options1: "Number",
      options2: "Array",
      options3: "String",
      options4: "Boolean",
      answer: 2,
    },
  ],
  Python: [
    {
      question: "Which keyword is used to define a function in Python?",
      options1: "function",
      options2: "define",
      options3: "def",
      options4: "fun",
      answer: 3,
    },
    {
      question: "What is the correct way to write a comment in Python?",
      options1: "// comment",
      options2: "# comment",
      options3: "<!-- comment -->",
      options4: "/* comment */",
      answer: 2,
    },
    {
      question: "Which data type is used to store text in Python?",
      options1: "int",
      options2: "float",
      options3: "str",
      options4: "bool",
      answer: 3,
    },
    {
      question: "Which function is used to get user input in Python?",
      options1: "read()",
      options2: "input()",
      options3: "scan()",
      options4: "get()",
      answer: 2,
    },
    {
      question: "What is the output of print(2 + 3 * 4)?",
      options1: "14",
      options2: "20",
      options3: "24",
      options4: "10",
      answer: 1,
    },
    {
      question: "Which of the following is a valid variable name?",
      options1: "2name",
      options2: "first-name",
      options3: "_name",
      options4: "class",
      answer: 3,
    },
    {
      question: "Which function returns the length of a list?",
      options1: "count()",
      options2: "size()",
      options3: "length()",
      options4: "len()",
      answer: 4,
    },
    {
    question: "How do you create a list in Python?",
    options1: "{}",
    options2: "[]",
    options3: "()",
    options4: "<>",
    answer: 2,
  },
  {
    question: "What does the 'type()' function return?",
    options1: "Data type of a variable",
    options2: "Variable name",
    options3: "Error code",
    options4: "Nothing",
    answer: 1,
  },
  {
    question: "Which keyword is used to create a loop in Python?",
    options1: "loop",
    options2: "repeat",
    options3: "for",
    options4: "iterate",
    answer: 3,
  },
],
  SQL: [
  {
    question: "What does SQL stand for?",
    options1: "Structured Query Language",
    options2: "Simple Query Language",
    options3: "Sequential Query Language",
    options4: "Standard Question Language",
    answer: 1,
  },
  {
    question: "Which SQL statement is used to fetch data from a database?",
    options1: "GET",
    options2: "SELECT",
    options3: "FETCH",
    options4: "RETRIEVE",
    answer: 2,
  },
  {
    question: "Which keyword is used to specify a table when inserting data?",
    options1: "INTO",
    options2: "TABLE",
    options3: "FROM",
    options4: "WHERE",
    answer: 1,
  },
  {
    question: "Which SQL statement is used to add new rows to a table?",
    options1: "INSERT INTO",
    options2: "ADD ROW",
    options3: "UPDATE",
    options4: "CREATE",
    answer: 1,
  },
  {
    question: "Which SQL clause is used to group rows that have the same values?",
    options1: "GROUP BY",
    options2: "ORDER BY",
    options3: "WHERE",
    options4: "HAVING",
    answer: 1,
  },
  {
    question: "Which SQL statement deletes data from a table?",
    options1: "DROP",
    options2: "DELETE",
    options3: "REMOVE",
    options4: "TRUNCATE",
    answer: 2,
  },
  {
    question: "How do you select all columns from a table named 'Customers'?",
    options1: "SELECT * FROM Customers;",
    options2: "SELECT all FROM Customers;",
    options3: "SELECT all_columns FROM Customers;",
    options4: "SELECT columns FROM Customers;",
    answer: 1,
  },
  {
    question: "Which clause is used to filter records in SQL?",
    options1: "FILTER BY",
    options2: "WHERE",
    options3: "GROUP BY",
    options4: "ORDER BY",
    answer: 2,
  },
  {
    question: "What type of SQL command is CREATE TABLE?",
    options1: "DDL (Data Definition Language)",
    options2: "DML (Data Manipulation Language)",
    options3: "DCL (Data Control Language)",
    options4: "TCL (Transaction Control Language)",
    answer: 1,
  },
  {
    question: "Which SQL statement is used to change the structure of a table?",
    options1: "MODIFY TABLE",
    options2: "CHANGE TABLE",
    options3: "ALTER TABLE",
    options4: "UPDATE TABLE",
    answer: 3,
  },
],
  C: [
  {
    question: "Which data type is used to store integer values in C?",
    options1: "int",
    options2: "char",
    options3: "float",
    options4: "double",
    answer: 1,
  },
  {
    question: "Which header file is required to use printf() function?",
    options1: "stdlib.h",
    options2: "stdio.h",
    options3: "string.h",
    options4: "conio.h",
    answer: 2,
  },
  {
    question: "What is the correct way to declare a variable in C?",
    options1: "int x;",
    options2: "int x = '5';",
    options3: "x int;",
    options4: "declare int x;",
    answer: 1,
  },
  {
    question: "What does the following code print?\n\nprintf(\"%d\", 10 + 5);",
    options1: "10",
    options2: "5",
    options3: "15",
    options4: "105",
    answer: 3,
  },
  {
    question: "Which operator is used to add two numbers?",
    options1: "+",
    options2: "-",
    options3: "*",
    options4: "/",
    answer: 1,
  },
  {
    question: "Which symbol is used to comment a single line in C?",
    options1: "/* comment */",
    options2: "// comment",
    options3: "# comment",
    options4: "<!-- comment -->",
    answer: 2,
  },
  {
    question: "What will the expression 5 % 2 evaluate to?",
    options1: "2",
    options2: "1",
    options3: "0",
    options4: "3",
    answer: 2,
  },
  {
    question: "Which loop executes at least once regardless of condition?",
    options1: "for",
    options2: "while",
    options3: "do...while",
    options4: "if",
    answer: 3,
  },
  {
    question: "How do you declare an array of 5 integers in C?",
    options1: "int arr[5];",
    options2: "int arr;",
    options3: "array arr[5];",
    options4: "int arr();",
    answer: 1,
  },
  {
    question: "What is the default return type of the main() function in C?",
    options1: "void",
    options2: "int",
    options3: "char",
    options4: "float",
    answer: 2,
  },
],
Cpp: [
  {
    question: "Which symbol is used to end a statement in C++?",
    options1: ";",
    options2: ".",
    options3: ":",
    options4: ",",
    answer: 1,
  },
  {
    question: "Which keyword is used to declare a variable in C++?",
    options1: "var",
    options2: "let",
    options3: "int",
    options4: "declare",
    answer: 3,
  },
  {
    question: "Which of the following is the correct way to print output in C++?",
    options1: "print('Hello');",
    options2: "cout << 'Hello';",
    options3: "printf('Hello');",
    options4: "Console.Write('Hello');",
    answer: 2,
  },
  {
    question: "Which header file is required for using cout in C++?",
    options1: "iostream",
    options2: "stdio.h",
    options3: "conio.h",
    options4: "string",
    answer: 1,
  },
  {
    question: "How do you write a single-line comment in C++?",
    options1: "// comment",
    options2: "# comment",
    options3: "/* comment */",
    options4: "<!-- comment -->",
    answer: 1,
  },
  {
    question: "Which of the following is used to store decimal values in C++?",
    options1: "char",
    options2: "int",
    options3: "float",
    options4: "bool",
    answer: 3,
  },
  {
    question: "What is the correct syntax to declare an array of 5 integers in C++?",
    options1: "int arr[5];",
    options2: "int arr = [5];",
    options3: "array arr(5);",
    options4: "int arr;",
    answer: 1,
  },
  {
    question: "Which of these is a valid loop in C++?",
    options1: "repeat",
    options2: "while",
    options3: "foreach",
    options4: "loop",
    answer: 2,
  },
  {
    question: "Which operator is used for addition in C++?",
    options1: "+",
    options2: "-",
    options3: "*",
    options4: "/",
    answer: 1,
  },
  {
    question: "What is the default return type of the main() function in C++?",
    options1: "void",
    options2: "int",
    options3: "char",
    options4: "float",
    answer: 2,
  },
],
BootStrap: [
  {
    question: "Which framework is Bootstrap primarily used for?",
    options1: "Front-end design",
    options2: "Back-end development",
    options3: "Database management",
    options4: "Operating system design",
    answer: 1,
  },
  {
    question: "Bootstrap is mainly written in which language?",
    options1: "JavaScript and CSS",
    options2: "HTML and CSS",
    options3: "HTML, CSS, and JavaScript",
    options4: "Python and CSS",
    answer: 3,
  },
  {
    question: "Which class in Bootstrap is used to create a basic button?",
    options1: ".btn",
    options2: ".button",
    options3: ".btn-basic",
    options4: ".btn-default",
    answer: 1,
  },
  {
    question: "What does the 'container' class do in Bootstrap?",
    options1: "Adds background color",
    options2: "Centers content and adds padding",
    options3: "Creates a flexbox layout",
    options4: "Makes text bold",
    answer: 2,
  },
  {
    question: "Which Bootstrap class is used to make text bold?",
    options1: ".text-bold",
    options2: ".fw-bold",
    options3: ".font-bold",
    options4: ".strong-text",
    answer: 2,
  },
  {
    question: "What is the purpose of the '.row' class in Bootstrap?",
    options1: "To create columns inside it",
    options2: "To center the text",
    options3: "To make text italic",
    options4: "To add background color",
    answer: 1,
  },
  {
    question: "Which file must be linked to use Bootstrap's CSS styles?",
    options1: "bootstrap.min.css",
    options2: "bootstrap.min.js",
    options3: "style.css",
    options4: "main.js",
    answer: 1,
  },
  {
    question: "Which Bootstrap class is used to make text center-aligned?",
    options1: ".center-text",
    options2: ".text-align-center",
    options3: ".text-center",
    options4: ".align-text-center",
    answer: 3,
  },
  {
    question: "Which Bootstrap component is used for showing quick information boxes?",
    options1: "Card",
    options2: "Jumbotron",
    options3: "Modal",
    options4: "Dropdown",
    answer: 1,
  },
  {
    question: "Which class makes a button take the full width of its parent in Bootstrap?",
    options1: ".btn-block",
    options2: ".btn-full",
    options3: ".btn-width",
    options4: ".btn-expand",
    answer: 1,
  },
],
React: [
  {
    question: "What is React primarily used for?",
    options1: "Building mobile apps",
    options2: "Building user interfaces",
    options3: "Managing databases",
    options4: "Creating server APIs",
    answer: 2,
  },
  {
    question: "React is a ____?",
    options1: "Framework",
    options2: "Library",
    options3: "Language",
    options4: "Database",
    answer: 2,
  },
  {
    question: "Which method is used to create components in React?",
    options1: "render()",
    options2: "createComponent()",
    options3: "Component()",
    options4: "buildComponent()",
    answer: 1,
  },
  {
    question: "Which of the following is used to create elements in React?",
    options1: "React.createElement()",
    options2: "React.makeElement()",
    options3: "React.element()",
    options4: "React.buildElement()",
    answer: 1,
  },
  {
    question: "What is the default file extension for React components?",
    options1: ".jsx",
    options2: ".js",
    options3: ".react",
    options4: ".component",
    answer: 1,
  },
  {
    question: "Which keyword is used to declare state variables in React functional components?",
    options1: "this.state",
    options2: "state()",
    options3: "useState",
    options4: "createState",
    answer: 3,
  },
  {
    question: "What is JSX?",
    options1: "JavaScript XML",
    options2: "Java Syntax Extension",
    options3: "JSON XML",
    options4: "JavaScript XHTML",
    answer: 1,
  },
  {
    question: "Which tag is used to return multiple elements in React?",
    options1: "<div>",
    options2: "<span>",
    options3: "<React.Fragment>",
    options4: "<section>",
    answer: 3,
  },
  {
    question: "Which command is used to start a new React project?",
    options1: "npm start react",
    options2: "npx create-react-app myApp",
    options3: "npm create react",
    options4: "node create react",
    answer: 2,
  },
  {
    question: "Which method is used to display content to the browser in React?",
    options1: "ReactDOM.render()",
    options2: "renderHTML()",
    options3: "display()",
    options4: "show()",
    answer: 1,
  },
],
AI: [
  {
    question: "What does AI stand for?",
    options1: "Automatic Intelligence",
    options2: "Artificial Intelligence",
    options3: "Automated Information",
    options4: "Advanced Interface",
    answer: 2,
  },
  {
    question: "Which of the following is an example of AI in daily life?",
    options1: "Smart assistants like Siri",
    options2: "Electric fan",
    options3: "Mechanical watch",
    options4: "Wooden chair",
    answer: 1,
  },
  {
    question: "Which programming language is most commonly used in AI?",
    options1: "Python",
    options2: "HTML",
    options3: "CSS",
    options4: "PHP",
    answer: 1,
  },
  {
    question: "Which type of AI can perform only specific tasks?",
    options1: "General AI",
    options2: "Narrow AI",
    options3: "Strong AI",
    options4: "Super AI",
    answer: 2,
  },
  {
    question: "Which of the following is a branch of AI?",
    options1: "Machine Learning",
    options2: "Database Management",
    options3: "Web Development",
    options4: "Graphic Designing",
    answer: 1,
  },
  {
    question: "Which company developed the AI assistant Alexa?",
    options1: "Google",
    options2: "Amazon",
    options3: "Apple",
    options4: "Microsoft",
    answer: 2,
  },
  {
    question: "Which AI technique is inspired by the human brain?",
    options1: "Neural Networks",
    options2: "Decision Trees",
    options3: "Regression Analysis",
    options4: "Sorting Algorithms",
    answer: 1,
  },
  {
    question: "Which Google product is powered by AI?",
    options1: "Google Translate",
    options2: "Google Chrome",
    options3: "Google Docs",
    options4: "Google Drive",
    answer: 1,
  },
  {
    question: "Which AI is used for speech recognition?",
    options1: "Computer Vision",
    options2: "Natural Language Processing",
    options3: "Expert System",
    options4: "Robotics",
    answer: 2,
  },
  {
    question: "Which of these is a popular AI framework?",
    options1: "TensorFlow",
    options2: "Bootstrap",
    options3: "React",
    options4: "Laravel",
    answer: 1,
  },
],
ASP: [
  {
    question: "What does ASP stand for?",
    options1: "Active Server Pages",
    options2: "Advanced Server Program",
    options3: "Application Server Pages",
    options4: "Automated Script Pages",
    answer: 1,
  },
  {
    question: "Which language is commonly used with ASP.NET?",
    options1: "C#",
    options2: "Python",
    options3: "PHP",
    options4: "Ruby",
    answer: 1,
  },
  {
    question: "ASP.NET is mainly used for developing?",
    options1: "Desktop Applications",
    options2: "Web Applications",
    options3: "Mobile Apps",
    options4: "Operating Systems",
    answer: 2,
  },
  {
    question: "Which framework does ASP.NET run on?",
    options1: ".NET Framework",
    options2: "Java Framework",
    options3: "Node.js",
    options4: "Spring Boot",
    answer: 1,
  },
  {
    question: "What is the file extension for ASP.NET Web Forms?",
    options1: ".aspx",
    options2: ".asp",
    options3: ".cshtml",
    options4: ".html",
    answer: 1,
  },
  {
    question: "Which company developed ASP.NET?",
    options1: "Microsoft",
    options2: "Google",
    options3: "IBM",
    options4: "Oracle",
    answer: 1,
  },
  {
    question: "What does IIS stand for in ASP.NET?",
    options1: "Internet Information Services",
    options2: "Internal Interface Server",
    options3: "Internet Integration System",
    options4: "Integrated Internet Software",
    answer: 1,
  },
  {
    question: "Which ASP.NET component is used for session management?",
    options1: "Session State",
    options2: "Cookie Storage",
    options3: "TempData",
    options4: "Database Cache",
    answer: 1,
  },
  {
    question: "Which markup is used in ASP.NET Web Forms?",
    options1: "HTML + Server Controls",
    options2: "Only HTML",
    options3: "Only CSS",
    options4: "Only JavaScript",
    answer: 1,
  },
  {
    question: "Which file stores application-level settings in ASP.NET?",
    options1: "web.config",
    options2: "appsettings.json",
    options3: "settings.ini",
    options4: "config.txt",
    answer: 1,
  },
],
Angular: [
  {
    question: "What is Angular?",
    options1: "A JavaScript framework for building web applications",
    options2: "A CSS framework",
    options3: "A database system",
    options4: "A server-side language",
    answer: 1,
  },
  {
    question: "Who developed Angular?",
    options1: "Google",
    options2: "Microsoft",
    options3: "Facebook",
    options4: "Amazon",
    answer: 1,
  },
  {
    question: "Which language is primarily used in Angular?",
    options1: "TypeScript",
    options2: "Python",
    options3: "PHP",
    options4: "Ruby",
    answer: 1,
  },
  {
    question: "What is the command to create a new Angular project?",
    options1: "ng new project-name",
    options2: "npm create angular-app",
    options3: "angular create project",
    options4: "ng start",
    answer: 1,
  },
  {
    question: "Which directive is used for conditional rendering in Angular?",
    options1: "*ngIf",
    options2: "*ngFor",
    options3: "*ngSwitch",
    options4: "*ngShow",
    answer: 1,
  },
  {
    question: "Which file defines the root module in Angular?",
    options1: "app.module.ts",
    options2: "main.ts",
    options3: "index.html",
    options4: "angular.json",
    answer: 1,
  },
  {
    question: "Which symbol is used for property binding in Angular?",
    options1: "[]",
    options2: "()",
    options3: "{}",
    options4: "<>",
    answer: 1,
  },
  {
    question: "Which CLI command runs the Angular application?",
    options1: "ng serve",
    options2: "npm run",
    options3: "ng start",
    options4: "node server.js",
    answer: 1,
  },
  {
    question: "Which decorator defines a component in Angular?",
    options1: "@Component",
    options2: "@NgModule",
    options3: "@Injectable",
    options4: "@Directive",
    answer: 1,
  },
  {
    question: "What does *ngFor directive do?",
    options1: "Iterates over a list of items",
    options2: "Applies CSS styles",
    options3: "Binds an event",
    options4: "Shows or hides elements",
    answer: 1,
  },
],
DSA: [
  {
    question: "Which data structure uses FIFO (First In First Out) order?",
    options1: "Queue",
    options2: "Stack",
    options3: "Linked List",
    options4: "Tree",
    answer: 1,
  },
  {
    question: "Which data structure uses LIFO (Last In First Out) order?",
    options1: "Stack",
    options2: "Queue",
    options3: "Heap",
    options4: "Graph",
    answer: 1,
  },
  {
    question: "What is the time complexity of binary search in a sorted array?",
    options1: "O(log n)",
    options2: "O(n)",
    options3: "O(n^2)",
    options4: "O(1)",
    answer: 1,
  },
  {
    question: "Which data structure is used to implement recursion?",
    options1: "Stack",
    options2: "Queue",
    options3: "Array",
    options4: "Graph",
    answer: 1,
  },
  {
    question: "Which sorting algorithm is the fastest in the average case?",
    options1: "Quick Sort",
    options2: "Bubble Sort",
    options3: "Selection Sort",
    options4: "Insertion Sort",
    answer: 1,
  },
  {
    question: "Which traversal method visits nodes in the order: Left, Root, Right?",
    options1: "Inorder Traversal",
    options2: "Preorder Traversal",
    options3: "Postorder Traversal",
    options4: "Level Order Traversal",
    answer: 1,
  },
  {
    question: "Which data structure is best for implementing a priority queue?",
    options1: "Heap",
    options2: "Array",
    options3: "Linked List",
    options4: "Stack",
    answer: 1,
  },
  {
    question: "Which algorithm is used to find the shortest path in a weighted graph?",
    options1: "Dijkstra's Algorithm",
    options2: "DFS",
    options3: "BFS",
    options4: "Prim's Algorithm",
    answer: 1,
  },
  {
    question: "Which operation is performed in O(1) time in a hash table?",
    options1: "Search",
    options2: "Sort",
    options3: "Traversal",
    options4: "Merge",
    answer: 1,
  },
  {
    question: "Which is an example of a linear data structure?",
    options1: "Array",
    options2: "Graph",
    options3: "Tree",
    options4: "Heap",
    answer: 1,
  },
],
CyberSecurity: [
  {
    question: "Which is the most common type of cyber attack?",
    options1: "Phishing",
    options2: "DDoS",
    options3: "Ransomware",
    options4: "SQL Injection",
    answer: 1,
  },
  {
    question: "What does 'HTTPS' stand for?",
    options1: "HyperText Transfer Protocol Secure",
    options2: "High Transfer Protocol System",
    options3: "Hyper Transfer Protocol Security",
    options4: "HyperText Transmission Secure",
    answer: 1,
  },
  {
    question: "Which of these is an example of a strong password?",
    options1: "P@ssw0rd#2025",
    options2: "123456",
    options3: "password",
    options4: "qwerty",
    answer: 1,
  },
  {
    question: "Which device is used to protect a network from unauthorized access?",
    options1: "Firewall",
    options2: "Router",
    options3: "Switch",
    options4: "Hub",
    answer: 1,
  },
  {
    question: "Which malware locks your files and demands payment?",
    options1: "Ransomware",
    options2: "Trojan",
    options3: "Worm",
    options4: "Spyware",
    answer: 1,
  },
  {
    question: "Which is NOT a type of malware?",
    options1: "Firewall",
    options2: "Virus",
    options3: "Worm",
    options4: "Trojan",
    answer: 1,
  },
  {
    question: "What does VPN stand for?",
    options1: "Virtual Private Network",
    options2: "Verified Protection Network",
    options3: "Virtual Protected Node",
    options4: "Verified Private Node",
    answer: 1,
  },
  {
    question: "Which cyber attack overloads a server with traffic?",
    options1: "DDoS",
    options2: "Phishing",
    options3: "Ransomware",
    options4: "Brute Force",
    answer: 1,
  },
  {
    question: "What is the main purpose of encryption?",
    options1: "To protect data confidentiality",
    options2: "To delete data",
    options3: "To increase internet speed",
    options4: "To compress data",
    answer: 1,
  },
  {
    question: "What is the first step in ethical hacking?",
    options1: "Reconnaissance",
    options2: "Exploitation",
    options3: "Scanning",
    options4: "Reporting",
    answer: 1,
  },
],
DataScience: [
  {
    question: "Which programming language is most commonly used in Data Science?",
    options1: "Python",
    options2: "C++",
    options3: "PHP",
    options4: "Java",
    answer: 1,
  },
  {
    question: "What does 'CSV' stand for in data files?",
    options1: "Comma-Separated Values",
    options2: "Common Server Variables",
    options3: "Central Source Variable",
    options4: "Character Separated Values",
    answer: 1,
  },
  {
    question: "Which library in Python is mainly used for data analysis?",
    options1: "Pandas",
    options2: "Django",
    options3: "Flask",
    options4: "NumPy",
    answer: 1,
  },
  {
    question: "What is the process of cleaning and preparing data called?",
    options1: "Data Wrangling",
    options2: "Data Mining",
    options3: "Data Modelling",
    options4: "Data Merging",
    answer: 1,
  },
  {
    question: "Which chart is best for showing proportions?",
    options1: "Pie Chart",
    options2: "Bar Chart",
    options3: "Line Chart",
    options4: "Histogram",
    answer: 1,
  },
  {
    question: "Which type of learning uses labeled data?",
    options1: "Supervised Learning",
    options2: "Unsupervised Learning",
    options3: "Reinforcement Learning",
    options4: "Deep Learning",
    answer: 1,
  },
  {
    question: "What is the main purpose of 'matplotlib' in Python?",
    options1: "Data Visualization",
    options2: "Data Cleaning",
    options3: "Data Analysis",
    options4: "Database Connection",
    answer: 1,
  },
  {
    question: "Which database type is used for large unstructured datasets?",
    options1: "NoSQL",
    options2: "SQL",
    options3: "Relational DB",
    options4: "Flat File",
    answer: 1,
  },
  {
    question: "What is a common file format for training datasets?",
    options1: "CSV",
    options2: "MP3",
    options3: "EXE",
    options4: "DOCX",
    answer: 1,
  },
  {
    question: "Which concept refers to the 'garbage in, garbage out' problem in data?",
    options1: "Data Quality",
    options2: "Data Visualization",
    options3: "Data Mining",
    options4: "Data Clustering",
    answer: 1,
  },
],




};

export default data;
