// data3.js
const data3 = {
 HTML: [
   {
    question: "What is the role of the 'role' attribute in HTML for accessibility?",
    options1: "Defines CSS behavior",
    options2: "Adds JavaScript events",
    options3: "Specifies semantic meaning for screen readers",
    options4: "Controls tab index",
    answer: 3,
  },
  {
    question: "Which HTML tag is used for bi-directional override of text direction?",
    options1: "<bdi>",
    options2: "<bdo>",
    options3: "<dir>",
    options4: "<ltr>",
    answer: 2,
  },
  {
    question: "What does the 'sandbox' attribute do in an <iframe>?",
    options1: "Disables all form inputs",
    options2: "Allows cross-origin data access",
    options3: "Applies security restrictions on iframe content",
    options4: "Increases iframe resolution",
    answer: 3,
  },
  {
    question: "Which attribute enables custom error messages in form validation?",
    options1: "data-message",
    options2: "title",
    options3: "custom-validity",
    options4: "oninvalid",
    answer: 4,
  },
  {
    question: "What does the 'contenteditable' attribute do?",
    options1: "Locks content for editing",
    options2: "Enables inline content editing by the user",
    options3: "Makes input fields hidden",
    options4: "Applies formatting styles",
    answer: 2,
  },
  {
    question: "Which tag is used to provide fallback content for browsers that don’t support scripts?",
    options1: "<fallback>",
    options2: "<alt-script>",
    options3: "<noscript>",
    options4: "<hide-script>",
    answer: 3,
  },
  {
    question: "What is the purpose of the <template> tag in HTML?",
    options1: "It is used for creating reusable CSS classes",
    options2: "It defines HTML fragments for JavaScript cloning",
    options3: "It defines a master layout",
    options4: "It holds server-side templates",
    answer: 2,
  },
  {
    question: "Which tag helps specify alternative media resources for different screen sizes?",
    options1: "<media>",
    options2: "<picture>",
    options3: "<imgset>",
    options4: "<source>",
    answer: 2,
  },
  {
    question: "What is the purpose of the 'hidden' attribute in HTML?",
    options1: "Visually hides elements but keeps them accessible",
    options2: "Completely hides an element from all rendering",
    options3: "Delays loading until needed",
    options4: "Sets an element to display: none",
    answer: 2,
  },
  {
    question: "Which of the following HTML tags supports the Shadow DOM?",
    options1: "<shadow>",
    options2: "<template>",
    options3: "<slot>",
    options4: "None of the above (it's via JS)",
    answer: 4,
  }
  ],
  CSS: [
  {
    question: "What does the 'will-change' property in CSS do?",
    options1: "Changes the page layout",
    options2: "Hints the browser for optimizations",
    options3: "Triggers media queries",
    options4: "Changes color scheme",
    answer: 2,
  },
  {
    question: "What is the specificity of a selector like 'ul li.active a'?",
    options1: "0,0,2,2",
    options2: "0,1,1,1",
    options3: "0,0,3,1",
    options4: "0,0,1,3",
    answer: 4,
  },
  {
    question: "Which property is used to control element rendering when scrolling?",
    options1: "scroll-behavior",
    options2: "overflow",
    options3: "contain",
    options4: "will-change",
    answer: 3,
  },
  {
    question: "What is the default stacking context in CSS?",
    options1: "z-index: 0",
    options2: "position: relative",
    options3: "The root element (html)",
    options4: "The <body> element",
    answer: 3,
  },
  {
    question: "Which media feature is used to apply styles based on device orientation?",
    options1: "max-width",
    options2: "min-resolution",
    options3: "orientation",
    options4: "aspect-ratio",
    answer: 3,
  },
  {
    question: "What does 'isolation: isolate;' do in CSS?",
    options1: "Creates a new stacking context",
    options2: "Resets parent styles",
    options3: "Prevents hover",
    options4: "Hides child elements",
    answer: 1,
  },
  {
    question: "Which of these values can 'display' property not take?",
    options1: "grid",
    options2: "inline-block",
    options3: "inline-table",
    options4: "float",
    answer: 4,
  },
  {
    question: "What does the 'clip-path' property do?",
    options1: "Crops elements into custom shapes",
    options2: "Resizes elements",
    options3: "Applies blur effects",
    options4: "Adds drop shadows",
    answer: 1,
  },
  {
    question: "How do you define a CSS custom property (variable)?",
    options1: "$main-color: red;",
    options2: "@main-color: red;",
    options3: "--main-color: red;",
    options4: "var-main-color: red;",
    answer: 3,
  },
  {
    question: "Which CSS pseudo-class targets elements being dragged?",
    options1: ":active",
    options2: ":drag",
    options3: ":dragging",
    options4: ":target",
    answer: 3,
  },
],
  JavaScript: [
  {
    question: "What does 'this' keyword refer to in a regular function?",
    options1: "Global object",
    options2: "Current function",
    options3: "Parent object",
    options4: "Window only",
    answer: 1,
  },
  {
    question: "Which method is used to create a deep copy of an object?",
    options1: "Object.assign()",
    options2: "JSON.parse(JSON.stringify())",
    options3: "Object.clone()",
    options4: "copyObject()",
    answer: 2,
  },
  {
    question: "What is the purpose of async/await in JavaScript?",
    options1: "To block execution",
    options2: "To run code faster",
    options3: "To handle asynchronous code more cleanly",
    options4: "To define variables",
    answer: 3,
  },
  {
    question: "Which method can be used to debounce a function?",
    options1: "throttle()",
    options2: "setInterval()",
    options3: "clearTimeout()",
    options4: "setTimeout() inside closure",
    answer: 4,
  },
  {
    question: "What is the difference between '==' and '===' in JavaScript?",
    options1: "Both compare strictly",
    options2: "'==' does type coercion, '===' does not",
    options3: "'===' does type coercion, '==' does not",
    options4: "No difference",
    answer: 2,
  },
  {
    question: "Which object does not exist in Node.js but exists in browser?",
    options1: "process",
    options2: "require",
    options3: "window",
    options4: "exports",
    answer: 3,
  },
  {
    question: "Which JavaScript feature allows defining template literals?",
    options1: "Single quotes",
    options2: "Backticks (` `)",
    options3: "Double quotes",
    options4: "Curly braces",
    answer: 2,
  },
  {
    question: "What does the 'map()' function do?",
    options1: "Filters elements",
    options2: "Loops through and modifies original array",
    options3: "Creates a new array with transformed elements",
    options4: "Deletes elements",
    answer: 3,
  },
  {
    question: "What will be the result of: `[...'abc']`?",
    options1: "['abc']",
    options2: "['a', 'b', 'c']",
    options3: "['a,b,c']",
    options4: "['a b c']",
    answer: 2,
  },
  {
    question: "Which operator can be used for optional chaining?",
    options1: "&&",
    options2: "||",
    options3: "?.",
    options4: "!",
    answer: 3,
  },
],
  Python: [
  {
    question: "What will be the output of: print({1, 2, 3} & {2, 3, 4})?",
    options1: "{1, 2, 3, 4}",
    options2: "{2, 3}",
    options3: "Error",
    options4: "[2, 3]",
    answer: 2,
  },
  {
    question: "What is the time complexity of accessing a value in a Python dictionary?",
    options1: "O(n)",
    options2: "O(log n)",
    options3: "O(1)",
    options4: "O(n log n)",
    answer: 3,
  },
  {
    question: "Which module is used for regular expressions in Python?",
    options1: "regex",
    options2: "re",
    options3: "regexp",
    options4: "pyregex",
    answer: 2,
  },
  {
    question: "What is the result of: all([0, 1, 2])?",
    options1: "True",
    options2: "False",
    options3: "Error",
    options4: "[False]",
    answer: 2,
  },
  {
    question: "Which Python feature allows iteration over multiple collections in parallel?",
    options1: "map()",
    options2: "zip()",
    options3: "join()",
    options4: "enumerate()",
    answer: 2,
  },
  {
    question: "What does the 'with' statement help in Python?",
    options1: "Managing function calls",
    options2: "Managing imports",
    options3: "Managing file/resource handling",
    options4: "Managing exceptions",
    answer: 3,
  },
  {
    question: "What does `__name__ == \"__main__\"` check?",
    options1: "If the file is imported",
    options2: "If it's a built-in module",
    options3: "If the script is run directly",
    options4: "If the script has a main()",
    answer: 3,
  },
  {
    question: "Which built-in function returns an iterable from multiple iterables?",
    options1: "map()",
    options2: "reduce()",
    options3: "zip()",
    options4: "lambda()",
    answer: 3,
  },
  {
    question: "What is the output of: print(list(filter(lambda x: x%2, [1,2,3,4])))?",
    options1: "[2, 4]",
    options2: "[1, 3]",
    options3: "[1, 2, 3, 4]",
    options4: "[0, 1]",
    answer: 2,
  },
  {
    question: "Which module is used to serialize and deserialize Python objects?",
    options1: "pickle",
    options2: "marshal",
    options3: "json",
    options4: "csv",
    answer: 1,
  },
],
SQL: [
  {
    question: "What is a correlated subquery?",
    options1: "A subquery executed once",
    options2: "A subquery that references outer query",
    options3: "A query without WHERE clause",
    options4: "A query that returns multiple tables",
    answer: 2,
  },
  {
    question: "Which SQL command is used to give privileges to users?",
    options1: "GRANT",
    options2: "ALLOW",
    options3: "PERMIT",
    options4: "ACCESS",
    answer: 1,
  },
  {
    question: "What does the SQL command 'EXPLAIN' do?",
    options1: "Shows query execution plan",
    options2: "Executes query",
    options3: "Deletes query",
    options4: "Modifies query",
    answer: 1,
  },
  {
    question: "Which isolation level prevents dirty reads in SQL transactions?",
    options1: "READ UNCOMMITTED",
    options2: "READ COMMITTED",
    options3: "REPEATABLE READ",
    options4: "SERIALIZABLE",
    answer: 2,
  },
  {
    question: "What does a window function in SQL do?",
    options1: "Performs aggregate calculations on a set of rows",
    options2: "Filters rows",
    options3: "Joins tables",
    options4: "Deletes rows",
    answer: 1,
  },
  {
    question: "Which SQL keyword is used to create an index?",
    options1: "CREATE INDEX",
    options2: "MAKE INDEX",
    options3: "ADD INDEX",
    options4: "INSERT INDEX",
    answer: 1,
  },
  {
    question: "What is the output of: SELECT CASE WHEN score >= 90 THEN 'A' ELSE 'F' END FROM grades;",
    options1: "Conditional result based on score",
    options2: "Error",
    options3: "List of scores",
    options4: "Alphabetical order",
    answer: 1,
  },
  {
    question: "Which SQL statement is used to rollback a transaction?",
    options1: "ROLLBACK",
    options2: "UNDO",
    options3: "CANCEL",
    options4: "REVERT",
    answer: 1,
  },
  {
    question: "Which clause is used with GROUP BY to filter grouped records?",
    options1: "WHERE",
    options2: "HAVING",
    options3: "FILTER",
    options4: "ORDER BY",
    answer: 2,
  },
  {
    question: "What is a recursive CTE in SQL?",
    options1: "A query that calls itself",
    options2: "A type of join",
    options3: "A transaction",
    options4: "An aggregate function",
    answer: 1,
  },
],
C:[
  {
    question: "What is the output of:\n\nint x = 3;\nprintf(\"%d\", x >> 1);",
    options1: "1",
    options2: "2",
    options3: "3",
    options4: "6",
    answer: 2,
  },
  {
    question: "What does 'static' keyword do when used with a variable inside a function?",
    options1: "Variable retains value between function calls",
    options2: "Variable is global",
    options3: "Variable is constant",
    options4: "Variable is volatile",
    answer: 1,
  },
  {
    question: "Which of the following is a correct syntax to declare a pointer to a function returning int?",
    options1: "int *func();",
    options2: "int (*func)();",
    options3: "int func*();",
    options4: "int func();*",
    answer: 2,
  },
  {
    question: "What is the behavior of accessing uninitialized local variables in C?",
    options1: "Contains garbage value",
    options2: "Zero initialized",
    options3: "Causes compile error",
    options4: "Automatically initialized to NULL",
    answer: 1,
  },
  {
    question: "What does this pointer arithmetic do?\n\nptr + 3 (where ptr is int*)",
    options1: "Adds 3 bytes to ptr",
    options2: "Adds 3 times size of int to ptr",
    options3: "Adds 3 bits to ptr",
    options4: "Error",
    answer: 2,
  },
  {
    question: "What is the result of the following code?\n\nchar *str = \"Hello\";\nstr[0] = 'h';",
    options1: "String becomes 'hello'",
    options2: "Runtime error",
    options3: "Compilation error",
    options4: "Undefined behavior",
    answer: 4,
  },
  {
    question: "What does the 'volatile' keyword specify?",
    options1: "Variable value can change unexpectedly",
    options2: "Variable is constant",
    options3: "Variable is static",
    options4: "Variable is local",
    answer: 1,
  },
  {
    question: "What is a memory leak in C?",
    options1: "Using uninitialized pointers",
    options2: "Not freeing dynamically allocated memory",
    options3: "Overwriting memory",
    options4: "Stack overflow",
    answer: 2,
  },
  {
    question: "Which function is used to resize previously allocated memory block?",
    options1: "malloc()",
    options2: "calloc()",
    options3: "realloc()",
    options4: "free()",
    answer: 3,
  },
  {
    question: "What is the output of the expression:\n\nsizeof(char) + sizeof(int) + sizeof(double)?",
    options1: "Depends on system but typically 13",
    options2: "3",
    options3: "7",
    options4: "Error",
    answer: 1,
  },
],
Cpp: [
  {
    question: "Which of the following is the correct syntax for defining a template function in C++?",
    options1: "template<typename T> void func(T a);",
    options2: "function<T> func(T a);",
    options3: "template<T> func(T a);",
    options4: "define<typename T> func(T a);",
    answer: 1,
  },
  {
    question: "Which of the following is NOT part of the C++ Standard Template Library (STL)?",
    options1: "vector",
    options2: "map",
    options3: "stack",
    options4: "tree",
    answer: 4,
  },
  {
    question: "What is the purpose of a virtual destructor in C++?",
    options1: "To speed up program execution",
    options2: "To ensure proper cleanup in polymorphic base classes",
    options3: "To allow multiple constructors",
    options4: "To make a class abstract",
    answer: 2,
  },
  {
    question: "Which C++11 feature allows creating anonymous functions?",
    options1: "Lambda expressions",
    options2: "Virtual functions",
    options3: "Function pointers",
    options4: "Templates",
    answer: 1,
  },
  {
    question: "Which smart pointer automatically deletes the managed object when the last reference to it is destroyed?",
    options1: "auto_ptr",
    options2: "shared_ptr",
    options3: "unique_ptr",
    options4: "weak_ptr",
    answer: 3,
  },
  {
    question: "Which keyword is used to prevent a method from being overridden in derived classes?",
    options1: "override",
    options2: "final",
    options3: "sealed",
    options4: "const",
    answer: 2,
  },
  {
    question: "In multithreading, which C++ header provides thread support?",
    options1: "<pthread>",
    options2: "<thread>",
    options3: "<multithread>",
    options4: "<concurrency>",
    answer: 2,
  },
  {
    question: "Which operator can be overloaded in C++?",
    options1: "?:",
    options2: "::",
    options3: "new",
    options4: "sizeof",
    answer: 3,
  },
  {
    question: "Which type of casting is considered safest in C++?",
    options1: "reinterpret_cast",
    options2: "dynamic_cast",
    options3: "static_cast",
    options4: "const_cast",
    answer: 2,
  },
  {
    question: "What does the noexcept specifier indicate in C++?",
    options1: "The function will not throw exceptions",
    options2: "The function has no parameters",
    options3: "The function will execute faster",
    options4: "The function cannot be inlined",
    answer: 1,
  },
],

BootStrap: [
  {
    question: "Which Bootstrap utility class is used to create a responsive fixed-width container?",
    options1: ".container",
    options2: ".container-fluid",
    options3: ".container-lg",
    options4: ".container-responsive",
    answer: 3,
  },
  {
    question: "In Bootstrap 5, which JavaScript plugin is required for modal functionality?",
    options1: "bootstrap.bundle.min.js",
    options2: "bootstrap.min.js",
    options3: "jquery.min.js",
    options4: "popper.js",
    answer: 1,
  },
  {
    question: "Which Bootstrap class combination is used for sticky top navigation?",
    options1: ".navbar-fixed",
    options2: ".sticky-navbar",
    options3: ".sticky-top",
    options4: ".navbar-top-fixed",
    answer: 3,
  },
  {
    question: "Which breakpoint in Bootstrap applies styles at screen width ≥ 1400px?",
    options1: "xl",
    options2: "xxl",
    options3: "lg",
    options4: "sm",
    answer: 2,
  },
  {
    question: "Which Bootstrap 5 helper class is used to visually hide content but keep it accessible to screen readers?",
    options1: ".sr-hidden",
    options2: ".visually-hidden",
    options3: ".screen-reader-only",
    options4: ".accessibility-hidden",
    answer: 2,
  },
  {
    question: "Which Bootstrap component uses data-bs-toggle and data-bs-target attributes?",
    options1: "Carousel",
    options2: "Collapse",
    options3: "Modal",
    options4: "All of the above",
    answer: 4,
  },
  {
    question: "In Bootstrap grid, how do you offset a column by 2 columns?",
    options1: ".col-offset-2",
    options2: ".offset-2",
    options3: ".ml-2",
    options4: ".pl-2",
    answer: 2,
  },
  {
    question: "Which Bootstrap utility class can be used to disable pointer events?",
    options1: ".no-pointer",
    options2: ".disable-pointer",
    options3: ".pe-none",
    options4: ".pointer-none",
    answer: 3,
  },
  {
    question: "What does the Bootstrap class '.g-0' do in a grid system?",
    options1: "Removes gutters between columns",
    options2: "Sets grid gap to zero",
    options3: "Aligns grid items to the top",
    options4: "Makes columns full width",
    answer: 1,
  },
  {
    question: "Which class is used to vertically align flex items in Bootstrap?",
    options1: ".align-items-vertical",
    options2: ".align-items-center",
    options3: ".align-vertical-center",
    options4: ".flex-align-center",
    answer: 2,
  },
],
React: [
  {
    question: "Which React hook can be used to build custom hooks?",
    options1: "useState",
    options2: "useCustom",
    options3: "Any built-in hook",
    options4: "useReducer only",
    answer: 3,
  },
  {
    question: "What is the purpose of React.lazy?",
    options1: "To load components lazily for performance",
    options2: "To delay rendering until data is fetched",
    options3: "To make components slower intentionally",
    options4: "To cache components",
    answer: 1,
  },
  {
    question: "Which API is used for server-side rendering in React?",
    options1: "ReactDOM.render",
    options2: "ReactDOMServer.renderToString",
    options3: "ReactServer.render",
    options4: "ReactSSR.renderToHTML",
    answer: 2,
  },
  {
    question: "Which method is used to hydrate a React app for server-side rendering?",
    options1: "ReactDOM.hydrate",
    options2: "ReactDOM.load",
    options3: "ReactDOM.attach",
    options4: "ReactDOM.renderSSR",
    answer: 1,
  },
  {
    question: "What is the main advantage of Concurrent Mode in React?",
    options1: "It allows rendering multiple components in parallel",
    options2: "It automatically fixes rendering bugs",
    options3: "It speeds up the DOM API",
    options4: "It eliminates the need for state",
    answer: 1,
  },
  {
    question: "Which of these is a new feature introduced in React 18?",
    options1: "Automatic batching",
    options2: "Hooks",
    options3: "Fragments",
    options4: "Context API",
    answer: 1,
  },
  {
    question: "What does Suspense in React do?",
    options1: "Prevents rendering until resources are loaded",
    options2: "Suspends the browser",
    options3: "Stops state updates",
    options4: "Pauses animations",
    answer: 1,
  },
  {
    question: "Which pattern is often used to share logic between components before hooks?",
    options1: "Higher Order Components (HOC)",
    options2: "Render Props",
    options3: "Mixins",
    options4: "All of the above",
    answer: 4,
  },
  {
    question: "Which hook is best suited for performance optimizations of expensive calculations?",
    options1: "useEffect",
    options2: "useMemo",
    options3: "useRef",
    options4: "useState",
    answer: 2,
  },
  {
    question: "What is React's Reconciliation process?",
    options1: "Updating the DOM efficiently using the Virtual DOM",
    options2: "Connecting state to props",
    options3: "Rendering HTML on the server",
    options4: "Synchronizing CSS with JavaScript",
    answer: 1,
  },
],
AI: [
  {
    question: "Which architecture is used in Transformer models like GPT?",
    options1: "Convolutional Layers",
    options2: "Recurrent Layers",
    options3: "Self-Attention Mechanism",
    options4: "Decision Trees",
    answer: 3,
  },
  {
    question: "Which optimization algorithm is most commonly used in deep learning?",
    options1: "Gradient Descent",
    options2: "K-Means",
    options3: "Apriori",
    options4: "Naive Bayes",
    answer: 1,
  },
  {
    question: "What is transfer learning in AI?",
    options1: "Training a model from scratch",
    options2: "Reusing a pre-trained model for a new task",
    options3: "Sharing model parameters between two models",
    options4: "Using AI in multiple languages",
    answer: 2,
  },
  {
    question: "Which loss function is commonly used in classification problems?",
    options1: "Mean Squared Error",
    options2: "Cross-Entropy Loss",
    options3: "Huber Loss",
    options4: "Hinge Loss",
    answer: 2,
  },
  {
    question: "Which AI model generates images from text descriptions?",
    options1: "BERT",
    options2: "DALL·E",
    options3: "AlphaGo",
    options4: "Watson",
    answer: 2,
  },
  {
    question: "Which concept in AI ensures that models do not overfit?",
    options1: "Regularization",
    options2: "Normalization",
    options3: "Augmentation",
    options4: "Optimization",
    answer: 1,
  },
  {
    question: "What is the vanishing gradient problem related to?",
    options1: "Training very deep neural networks",
    options2: "Overfitting in decision trees",
    options3: "Slow k-means convergence",
    options4: "Bias in datasets",
    answer: 1,
  },
  {
    question: "Which AI technique uses two networks competing against each other?",
    options1: "RNN",
    options2: "CNN",
    options3: "GAN",
    options4: "SVM",
    answer: 3,
  },
  {
    question: "Which of the following is a reinforcement learning algorithm?",
    options1: "Q-Learning",
    options2: "Naive Bayes",
    options3: "Logistic Regression",
    options4: "KNN",
    answer: 1,
  },
  {
    question: "Which type of neural network is most effective for text generation?",
    options1: "CNN",
    options2: "RNN with LSTM/GRU",
    options3: "GAN",
    options4: "SVM",
    answer: 2,
  },
],
ASP: [
  {
    question: "Which design pattern is heavily used in ASP.NET MVC?",
    options1: "Front Controller",
    options2: "Observer",
    options3: "Factory",
    options4: "Builder",
    answer: 1,
  },
  {
    question: "What is the role of Global.asax in ASP.NET?",
    options1: "Application-level event handling",
    options2: "Database configuration",
    options3: "Session data storage",
    options4: "View rendering",
    answer: 1,
  },
  {
    question: "Which middleware is responsible for routing in ASP.NET Core?",
    options1: "Endpoint Routing Middleware",
    options2: "Session Middleware",
    options3: "Authentication Middleware",
    options4: "MVC Middleware",
    answer: 1,
  },
  {
    question: "What is Dependency Injection in ASP.NET Core?",
    options1: "Injecting required dependencies into classes",
    options2: "Injecting HTML into views",
    options3: "Injecting SQL queries into controllers",
    options4: "Injecting styles into layouts",
    answer: 1,
  },
  {
    question: "Which protocol does SignalR in ASP.NET use for real-time communication?",
    options1: "WebSockets",
    options2: "FTP",
    options3: "SMTP",
    options4: "IMAP",
    answer: 1,
  },
  {
    question: "Which method in ASP.NET Core is used to configure services?",
    options1: "ConfigureServices",
    options2: "ConfigureApp",
    options3: "AddServices",
    options4: "SetupServices",
    answer: 1,
  },
  {
    question: "What is the default JSON serializer in ASP.NET Core?",
    options1: "System.Text.Json",
    options2: "Newtonsoft.Json",
    options3: "FastJson",
    options4: "Json.NetCore",
    answer: 1,
  },
  {
    question: "In Entity Framework, which method is used to retrieve data?",
    options1: "ToList()",
    options2: "ExecuteQuery()",
    options3: "Fetch()",
    options4: "Run()",
    answer: 1,
  },
  {
    question: "Which feature in ASP.NET Core allows environment-specific configurations?",
    options1: "appsettings.{Environment}.json",
    options2: "config.env",
    options3: "web.config",
    options4: "env.settings",
    answer: 1,
  },
  {
    question: "Which testing framework is commonly used with ASP.NET Core?",
    options1: "xUnit",
    options2: "JUnit",
    options3: "Mocha",
    options4: "RSpec",
    answer: 1,
  },
],
Angular: [
  {
    question: "What is Angular Ivy?",
    options1: "A next-generation rendering engine",
    options2: "A CSS library",
    options3: "A form validation tool",
    options4: "A router service",
    answer: 1,
  },
  {
    question: "Which method is used to subscribe to Observables in Angular?",
    options1: ".subscribe()",
    options2: ".listen()",
    options3: ".observe()",
    options4: ".watch()",
    answer: 1,
  },
  {
    question: "What is the role of NgZone in Angular?",
    options1: "Manages change detection and asynchronous tasks",
    options2: "Stores application state",
    options3: "Handles routing",
    options4: "Applies styles",
    answer: 1,
  },
  {
    question: "What is Ahead-of-Time (AOT) compilation in Angular?",
    options1: "Compiling templates during build time",
    options2: "Compiling templates at runtime",
    options3: "Lazy loading modules",
    options4: "Optimizing images",
    answer: 1,
  },
  {
    question: "What is the main benefit of OnPush change detection strategy?",
    options1: "Improves performance by checking only when inputs change",
    options2: "Checks all components on every event",
    options3: "Removes the need for change detection",
    options4: "Increases memory usage",
    answer: 1,
  },
  {
    question: "What is a lazy-loaded module in Angular?",
    options1: "A module loaded only when needed",
    options2: "A module loaded at app start",
    options3: "A module that never loads",
    options4: "A test-only module",
    answer: 1,
  },
  {
    question: "What is the difference between Subject and BehaviorSubject in Angular RxJS?",
    options1: "BehaviorSubject stores the latest value, Subject does not",
    options2: "Subject stores latest value, BehaviorSubject does not",
    options3: "Both are identical",
    options4: "Neither stores values",
    answer: 1,
  },
  {
    question: "Which Angular decorator is used for creating custom pipes?",
    options1: "@Pipe",
    options2: "@Component",
    options3: "@Injectable",
    options4: "@Directive",
    answer: 1,
  },
  {
    question: "What is the default strategy for Angular routing?",
    options1: "PathLocationStrategy",
    options2: "HashLocationStrategy",
    options3: "HistoryLocationStrategy",
    options4: "DefaultLocationStrategy",
    answer: 1,
  },
  {
    question: "What is ViewEncapsulation in Angular?",
    options1: "Defines how styles are scoped to components",
    options2: "Encapsulates HTML templates",
    options3: "Encapsulates services",
    options4: "Encapsulates modules",
    answer: 1,
  },
],
DSA: [
  {
    question: "Which algorithm uses memoization to optimize recursive solutions?",
    options1: "Dynamic Programming",
    options2: "Greedy Algorithm",
    options3: "Backtracking",
    options4: "Branch and Bound",
    answer: 1,
  },
  {
    question: "What is the time complexity of building a heap from an unsorted array?",
    options1: "O(n)",
    options2: "O(n log n)",
    options3: "O(log n)",
    options4: "O(n^2)",
    answer: 1,
  },
  {
    question: "Which algorithm is best for solving the Travelling Salesman Problem exactly?",
    options1: "Dynamic Programming",
    options2: "Greedy Algorithm",
    options3: "Dijkstra's Algorithm",
    options4: "Kruskal's Algorithm",
    answer: 1,
  },
  {
    question: "In Red-Black Trees, what is the maximum height for n nodes?",
    options1: "2 log2(n+1)",
    options2: "n",
    options3: "log2(n)",
    options4: "n/2",
    answer: 1,
  },
  {
    question: "Which shortest path algorithm works with negative weights but no negative cycles?",
    options1: "Bellman-Ford",
    options2: "Dijkstra",
    options3: "Floyd-Warshall",
    options4: "Prim's",
    answer: 1,
  },
  {
    question: "Which algorithm solves the Knapsack problem optimally?",
    options1: "Dynamic Programming",
    options2: "Greedy Algorithm",
    options3: "DFS",
    options4: "BFS",
    answer: 1,
  },
  {
    question: "Which advanced data structure supports O(1) amortized time for insert and delete?",
    options1: "Hash Table",
    options2: "Binary Search Tree",
    options3: "Heap",
    options4: "AVL Tree",
    answer: 1,
  },
  {
    question: "Which algorithm is used in pattern matching for strings?",
    options1: "KMP Algorithm",
    options2: "Dijkstra",
    options3: "Prim's",
    options4: "Merge Sort",
    answer: 1,
  },
  {
    question: "What is the complexity of Floyd-Warshall algorithm?",
    options1: "O(n^3)",
    options2: "O(n^2)",
    options3: "O(log n)",
    options4: "O(n)",
    answer: 1,
  },
  {
    question: "Which tree structure is used in segment trees for range queries?",
    options1: "Binary Tree",
    options2: "B-Tree",
    options3: "Red-Black Tree",
    options4: "AVL Tree",
    answer: 1,
  },
],
CyberSecurity: [
  {
    question: "Which cryptographic method is used in blockchain for digital signatures?",
    options1: "Elliptic Curve Cryptography",
    options2: "AES",
    options3: "DES",
    options4: "Diffie-Hellman",
    answer: 1,
  },
  {
    question: "Which type of attack exploits a race condition in software?",
    options1: "TOCTOU Attack",
    options2: "Phishing",
    options3: "DDoS",
    options4: "Buffer Overflow",
    answer: 1,
  },
  {
    question: "Which advanced persistent threat group is linked to state-sponsored cyber espionage?",
    options1: "APT28",
    options2: "APT404",
    options3: "APT12",
    options4: "APT99",
    answer: 1,
  },
  {
    question: "What is the primary function of a honeypot in cybersecurity?",
    options1: "To lure and analyze attackers",
    options2: "To block all incoming traffic",
    options3: "To encrypt user data",
    options4: "To scan networks",
    answer: 1,
  },
  {
    question: "Which attack manipulates transactions in real-time by hijacking a web session?",
    options1: "Man-in-the-Browser",
    options2: "Cross-Site Scripting",
    options3: "DNS Spoofing",
    options4: "SQL Injection",
    answer: 1,
  },
  {
    question: "Which encryption method is quantum-resistant?",
    options1: "Lattice-based Cryptography",
    options2: "RSA",
    options3: "AES",
    options4: "ECC",
    answer: 1,
  },
  {
    question: "Which protocol is used for secure remote login?",
    options1: "SSH",
    options2: "Telnet",
    options3: "HTTP",
    options4: "FTP",
    answer: 1,
  },
  {
    question: "Which vulnerability occurs due to improper input validation in XML processing?",
    options1: "XXE (XML External Entity) Attack",
    options2: "XSS",
    options3: "SQL Injection",
    options4: "CSRF",
    answer: 1,
  },
  {
    question: "Which tool is used for penetration testing and ethical hacking?",
    options1: "Metasploit",
    options2: "Notepad++",
    options3: "Photoshop",
    options4: "Postman",
    answer: 1,
  },
  {
    question: "Which attack involves sending malicious ARP messages to a LAN?",
    options1: "ARP Spoofing",
    options2: "DNS Spoofing",
    options3: "Ping of Death",
    options4: "Clickjacking",
    answer: 1,
  },
],
DataScience: [
  {
    question: "Which neural network architecture is best for image recognition?",
    options1: "Convolutional Neural Network (CNN)",
    options2: "Recurrent Neural Network (RNN)",
    options3: "GAN",
    options4: "Autoencoder",
    answer: 1,
  },
  {
    question: "Which algorithm is used for anomaly detection?",
    options1: "Isolation Forest",
    options2: "K-Means",
    options3: "Decision Tree",
    options4: "Linear Regression",
    answer: 1,
  },
  {
    question: "What is the main advantage of using XGBoost?",
    options1: "High performance and regularization",
    options2: "Simple to implement",
    options3: "No need for data cleaning",
    options4: "Works only on images",
    answer: 1,
  },
  {
    question: "Which method prevents overfitting in deep learning models?",
    options1: "Dropout",
    options2: "Batch Normalization",
    options3: "Early Stopping",
    options4: "All of the above",
    answer: 4,
  },
  {
    question: "Which type of learning is used in recommendation systems like Netflix?",
    options1: "Collaborative Filtering",
    options2: "Supervised Learning",
    options3: "Reinforcement Learning",
    options4: "Unsupervised Learning",
    answer: 1,
  },
  {
    question: "Which metric is most useful for imbalanced classification problems?",
    options1: "F1-score",
    options2: "Accuracy",
    options3: "Mean Squared Error",
    options4: "R-squared",
    answer: 1,
  },
  {
    question: "Which optimization algorithm is commonly used in deep learning?",
    options1: "Adam",
    options2: "Gradient Descent",
    options3: "SGD",
    options4: "RMSprop",
    answer: 1,
  },
  {
    question: "Which data structure is used to store sparse matrices efficiently?",
    options1: "CSR (Compressed Sparse Row)",
    options2: "Array",
    options3: "List",
    options4: "Hash Table",
    answer: 1,
  },
  {
    question: "Which process involves creating synthetic data to balance classes?",
    options1: "SMOTE",
    options2: "Oversampling",
    options3: "Undersampling",
    options4: "Normalization",
    answer: 1,
  },
  {
    question: "Which library provides high-level APIs for TensorFlow?",
    options1: "Keras",
    options2: "NumPy",
    options3: "Pandas",
    options4: "Matplotlib",
    answer: 1,
  },
],



};

export default data3;
