const data2 = {
  HTML: [
    {
      question: "Which HTML5 element is used to define navigation links?",
      options1: "<nav>",
      options2: "<navigate>",
      options3: "<navigation>",
      options4: "<link>",
      answer: 1,
    },
    {
      question: "What does the 'defer' attribute do in a script tag?",
      options1: "Loads script after page load",
      options2: "Stops script from executing",
      options3: "Loads script before parsing",
      options4: "Executes script after HTML is parsed",
      answer: 4,
    },
    {
      question: "Which tag is used to define a caption for a table?",
      options1: "<caption>",
      options2: "<title>",
      options3: "<header>",
      options4: "<head>",
      answer: 1,
    },
    {
      question: "Which input type allows selecting multiple files?",
      options1: "type='files'",
      options2: "type='file' with multiple",
      options3: "type='upload'",
      options4: "type='select-multiple'",
      answer: 2,
    },
    {
      question: "What is the correct HTML tag to embed an SVG?",
      options1: "<canvas>",
      options2: "<svg>",
      options3: "<shape>",
      options4: "<draw>",
      answer: 2,
    },
    {
      question: "What does the 'contenteditable' attribute do?",
      options1: "Makes content readonly",
      options2: "Allows editing of content in browser",
      options3: "Hides content",
      options4: "Styles the content",
      answer: 2,
    },
    {
      question: "Which tag defines an interactive fieldset legend?",
      options1: "<label>",
      options2: "<title>",
      options3: "<legend>",
      options4: "<caption>",
      answer: 3,
    },
    {
      question: "Which attribute is used to link a label to an input?",
      options1: "link",
      options2: "name",
      options3: "for",
      options4: "id",
      answer: 3,
    },
    {
      question: "What is the correct element for a progress bar?",
      options1: "<progress>",
      options2: "<bar>",
      options3: "<loader>",
      options4: "<meter>",
      answer: 1,
    },
    {
      question: "Which HTML tag is used to define an internal style sheet?",
      options1: "<css>",
      options2: "<style>",
      options3: "<script>",
      options4: "<headstyle>",
      answer: 2,
    },
  ],

  CSS: [
    {
      question: "Which CSS property controls text size?",
      options1: "text-size",
      options2: "font-size",
      options3: "size",
      options4: "text-font",
      answer: 2,
    },
    {
      question: "Which CSS property is used to change the element's background color?",
      options1: "color",
      options2: "background-color",
      options3: "bgcolor",
      options4: "background",
      answer: 2,
    },
    {
      question: "Which CSS value makes an element invisible but keeps its space?",
      options1: "display: none",
      options2: "opacity: 0",
      options3: "visibility: hidden",
      options4: "hidden: true",
      answer: 3,
    },
    {
      question: "Which selector selects all paragraph elements inside div?",
      options1: "div p",
      options2: "div > p",
      options3: "div + p",
      options4: "p div",
      answer: 1,
    },
    {
      question: "Which property controls the space between letters?",
      options1: "letter-spacing",
      options2: "spacing",
      options3: "word-spacing",
      options4: "line-height",
      answer: 1,
    },
    {
      question: "Which unit is relative to the root element's font size?",
      options1: "em",
      options2: "px",
      options3: "rem",
      options4: "%",
      answer: 3,
    },
    {
      question: "Which CSS feature allows reusing variables?",
      options1: "CSS Functions",
      options2: "SASS only",
      options3: "CSS Variables",
      options4: "Classes",
      answer: 3,
    },
    {
      question: "Which property sets the stacking order of elements?",
      options1: "position",
      options2: "float",
      options3: "z-index",
      options4: "display",
      answer: 3,
    },
    {
      question: "Which value of position makes element fixed to viewport?",
      options1: "relative",
      options2: "absolute",
      options3: "fixed",
      options4: "sticky",
      answer: 3,
    },
    {
      question: "How do you apply style to an element with id='header'?",
      options1: "#header", 
      options2: ".header", 
      options3: "header", 
      options4: "id.header", 
      answer: 1,
    },
  ],

  JavaScript: [
    {
      question: "Which method converts JSON string to object?",
      options1: "JSON.toObject()",
      options2: "JSON.parse()",
      options3: "JSON.stringify()",
      options4: "JSON.convert()",
      answer: 2,
    },
    {
      question: "What is a Promise in JavaScript?",
      options1: "A type of variable",
      options2: "An async computation placeholder",
      options3: "An object loop",
      options4: "A math function",
      answer: 2,
    },
    {
      question: "Which keyword is used to create a constant variable?",
      options1: "var",
      options2: "let",
      options3: "const",
      options4: "static",
      answer: 3,
    },
    {
      question: "What will typeof null return?",
      options1: "null",
      options2: "undefined",
      options3: "object",
      options4: "string",
      answer: 3,
    },
    {
      question: "Which method adds element at end of an array?",
      options1: "push()",
      options2: "pop()",
      options3: "shift()",
      options4: "unshift()",
      answer: 1,
    },
    {
      question: "What is the output of '2' + 2 in JavaScript?",
      options1: "4",
      options2: "22",
      options3: "NaN",
      options4: "undefined",
      answer: 2,
    },
    {
      question: "What is the default value of an uninitialized variable?",
      options1: "null",
      options2: "0",
      options3: "NaN",
      options4: "undefined",
      answer: 4,
    },
    {
      question: "How do you write an arrow function?",
      options1: "function => () {}",
      options2: "() => {}",
      options3: "=> function()",
      options4: "() => function",
      answer: 2,
    },
    {
      question: "Which method removes the last element from array?",
      options1: "pop()",
      options2: "shift()",
      options3: "remove()",
      options4: "splice()",
      answer: 1,
    },
    {
      question: "Which loop runs at least once even if condition is false?",
      options1: "for",
      options2: "while",
      options3: "do...while",
      options4: "foreach",
      answer: 3,
    },
  ],

  Python: [
    {
      question: "What will be the output of the expression 3 * 1**3 in Python?",
      options1: "27",
      options2: "3",
      options3: "1",
      options4: "9",
      answer: 2,
    },
    {
      question: "Which of the following is used to define a block of code in Python?",
      options1: "Curly braces {}",
      options2: "Parentheses ()",
      options3: "Indentation",
      options4: "Quotation marks",
      answer: 3,
    },
    {
      question: "What is the output of: print(bool(0), bool(3.14159), bool(-3), bool(1.0+1j))?",
      options1: "False True True True",
      options2: "True True False True",
      options3: "False False False False",
      options4: "True False True False",
      answer: 1,
    },
    {
      question: "Which of the following is not a valid way to import modules in Python?",
      options1: "import math",
      options2: "from math import *",
      options3: "include math",
      options4: "from math import sqrt",
      answer: 3,
    },
    {
      question: "What is the output of the following code: print('5' + '4')?",
      options1: "9",
      options2: "54",
      options3: "Error",
      options4: "20",
      answer: 2,
    },
    {
      question: "Which of the following methods can be used to convert a string to lowercase?",
      options1: "lower()",
      options2: "tolower()",
      options3: "strlower()",
      options4: "down()",
      answer: 1,
    },
    {
      question: "What does the // operator in Python do?",
      options1: "Performs division and returns a float",
      options2: "Performs integer division",
      options3: "Performs exponential operation",
      options4: "Performs bitwise XOR",
      answer: 2,
    },
    {
      question: "Which of the following is a correct lambda function?",
      options1: "lambda x, y: x + y",
      options2: "def lambda(x, y): return x + y",
      options3: "lambda(x, y) x + y",
      options4: "def lambda: x + y",
      answer: 1,
    },
    {
      question: "Which Python built-in function returns a sequence of numbers starting from 0 by default?",
      options1: "list()",
      options2: "sequence()",
      options3: "range()",
      options4: "enumerate()",
      answer: 3,
    },
    {
      question: "What will be the output of: print([i for i in range(5) if i % 2])?",
      options1: "[0, 2, 4]",
      options2: "[1, 3]",
      options3: "[0, 1, 2, 3, 4]",
      options4: "[2, 3]",
      answer: 2,
    },
  ],

  SQL: [
    {
      question: "Which SQL clause is used to filter the results returned by a SELECT statement?",
      options1: "WHERE",
      options2: "ORDER BY",
      options3: "GROUP BY",
      options4: "HAVING",
      answer: 1,
    },
    {
      question: "What will be the result of: SELECT COUNT(*) FROM employees WHERE salary > 50000?",
      options1: "Counts employees with salary more than 50k",
      options2: "Gives list of salaries",
      options3: "Returns max salary",
      options4: "Returns all employee names",
      answer: 1,
    },
    {
      question: "Which function is used to remove duplicate rows from a query result?",
      options1: "UNIQUE",
      options2: "NO DUPLICATE",
      options3: "DISTINCT",
      options4: "REMOVE DUPLICATE",
      answer: 3,
    },
    {
      question: "Which SQL keyword is used to sort the result-set?",
      options1: "ORDER BY",
      options2: "SORT",
      options3: "GROUP",
      options4: "RANK",
      answer: 1,
    },
    {
      question: "What does the following SQL do? SELECT AVG(salary) FROM employees;",
      options1: "Returns total salary",
      options2: "Returns max salary",
      options3: "Returns average salary",
      options4: "Returns salaries",
      answer: 3,
    },
    {
      question: "What type of JOIN returns all rows from the left table and matching rows from the right?",
      options1: "INNER JOIN",
      options2: "LEFT JOIN",
      options3: "RIGHT JOIN",
      options4: "FULL JOIN",
      answer: 2,
    },
    {
      question: "Which statement is used to delete all data from a table but not the table itself?",
      options1: "REMOVE",
      options2: "DELETE",
      options3: "TRUNCATE",
      options4: "DROP",
      answer: 3,
    },
    {
      question: "What does the PRIMARY KEY constraint do?",
      options1: "Allows duplicate values",
      options2: "Ensures a column has unique values",
      options3: "Links two tables",
      options4: "Sorts records",
      answer: 2,
    },
    {
      question: "Which of the following SQL statements is valid?",
      options1: "SELECT name FROM users WHERE age = 25;",
      options2: "GET name FROM users IF age = 25;",
      options3: "PULL name FROM users WHERE age = 25;",
      options4: "FETCH name FROM users AT age = 25;",
      answer: 1,
    },
    {
      question: "Which keyword is used to modify existing records in a table?",
      options1: "CHANGE",
      options2: "MODIFY",
      options3: "UPDATE",
      options4: "ALTER",
      answer: 3,
    },
  ],
  // c programming
  C: [
    {
      question: "Which header file is essential for using printf and scanf in C?",
      options1: "stdlib.h",
      options2: "conio.h",
      options3: "stdio.h",
      options4: "string.h",
      answer: 3,
    },
    {
      question: "What will be the result of: int x = 10 / 4; in C?",
      options1: "2.5",
      options2: "2",
      options3: "3",
      options4: "4",
      answer: 3,
    },
    {
      question: "Which operator is used to allocate memory dynamically in C?",
      options1: "malloc",
      options2: "alloc",
      options3: "new",
      options4: "calloc",
      answer: 1,
    },
    {
      question: "What does the 'sizeof' operator return?",
      options1: "Address",
      options2: "Size in bytes",
      options3: "Bit length",
      options4: "Number of elements",
      answer: 2,
    },
    {
      question: "Which of the following is used to define a constant in C?",
      options1: "let",
      options2: "const",
      options3: "#define",
      options4: "static",
      answer: 3,
    },
    {
      question: "What is a pointer in C?",
      options1: "A variable that stores address of another variable",
      options2: "A function",
      options3: "An array",
      options4: "None",
      answer: 1,
    },
    {
      question: "Which function is used to read a character from the console in C?",
      options1: "scanf()",
      options2: "cin",
      options3: "getchar()",
      options4: "input()",
      answer: 3,
    },
    {
      question: "Which keyword is used to prevent modification of a variable through a pointer?",
      options1: "static",
      options2: "restrict",
      options3: "const",
      options4: "volatile",
      answer: 3,
    },
    {
      question: "Which control statement is used to skip the rest of a loop iteration?",
      options1: "stop",
      options2: "skip",
      options3: "continue",
      options4: "exit",
      answer: 3,
    },
    {
      question: "What is the purpose of the 'return 0;' statement in C?",
      options1: "Terminates loop",
      options2: "Ends main function and returns success",
      options3: "Starts program",
      options4: "Stops compiler",
      answer: 2,
    },
  ],
  Cpp: [
    {
      question: "Which of the following is used to define a class in C++?",
      options1: "class",
      options2: "define",
      options3: "struct",
      options4: "object",
      answer: 1,
    },
    {
      question: "Which feature of OOP allows the same function name to be used for different types?",
      options1: "Abstraction",
      options2: "Encapsulation",
      options3: "Polymorphism",
      options4: "Inheritance",
      answer: 3,
    },
    {
      question: "Which of these is the correct syntax for creating a pointer in C++?",
      options1: "int p = &x;",
      options2: "int *p = &x;",
      options3: "int &p = x;",
      options4: "int pointer p = x;",
      answer: 2,
    },
    {
      question: "What does the 'new' keyword do in C++?",
      options1: "Deletes an object",
      options2: "Declares a variable",
      options3: "Allocates memory dynamically",
      options4: "Initializes class",
      answer: 3,
    },
    {
      question: "Which of the following is used for exception handling in C++?",
      options1: "catch-throw",
      options2: "try-catch",
      options3: "if-else",
      options4: "error-try",
      answer: 2,
    },
    {
      question: "Which concept allows derived classes to have properties of the base class?",
      options1: "Polymorphism",
      options2: "Abstraction",
      options3: "Inheritance",
      options4: "Encapsulation",
      answer: 3,
    },
    {
      question: "Which header file is required for using std::cout in C++?",
      options1: "iostream",
      options2: "stdio.h",
      options3: "conio.h",
      options4: "string",
      answer: 1,
    },
    {
      question: "What will 'delete' operator do in C++?",
      options1: "Allocate memory",
      options2: "Free dynamic memory",
      options3: "Delete variable",
      options4: "End program",
      answer: 2,
    },
    {
      question: "What is the default access specifier for members of a class in C++?",
      options1: "public",
      options2: "private",
      options3: "protected",
      options4: "internal",
      answer: 2,
    },
    {
      question: "Which symbol is used for the scope resolution operator in C++?",
      options1: ".",
      options2: "::",
      options3: "->",
      options4: "=>",
      answer: 2,
    },
  ],
  BootStrap:[
    {
      question: "Which class in Bootstrap is used to make an image responsive?",
      options1: ".img-responsive",
      options2: ".image-fluid",
      options3: ".img-fluid",
      options4: ".responsive-img",
      answer: 3,
    },
    {
      question: "What is the default flex direction in Bootstrap's d-flex class?",
      options1: "column",
      options2: "row",
      options3: "row-reverse",
      options4: "none",
      answer: 2,
    },
    {
      question: "Which Bootstrap class is used to hide an element only on small devices?",
      options1: ".d-sm-none",
      options2: ".d-none-sm",
      options3: ".hidden-sm",
      options4: ".d-hide-sm",
      answer: 1,
    },
    {
      question: "Which class is used for a dark navigation bar in Bootstrap?",
      options1: ".navbar-dark bg-dark",
      options2: ".navbar-light bg-light",
      options3: ".navbar-black",
      options4: ".navbar-inverse",
      answer: 1,
    },
    {
      question: "Which of the following is used to create a button group in Bootstrap?",
      options1: ".btn-collection",
      options2: ".btn-cluster",
      options3: ".btn-group",
      options4: ".button-group",
      answer: 3,
    },
    {
      question: "What is the Bootstrap grid system based on?",
      options1: "10 columns",
      options2: "12 columns",
      options3: "16 columns",
      options4: "24 columns",
      answer: 2,
    },
    {
      question: "Which class is used to create a jumbotron in Bootstrap 4?",
      options1: ".jumbotron",
      options2: ".jumbo",
      options3: ".jmb",
      options4: ".hero",
      answer: 1,
    },
    {
      question: "Which utility class is used to set margin in Bootstrap?",
      options1: ".padding",
      options2: ".mg",
      options3: ".m-",
      options4: ".mr-",
      answer: 3,
    },
    {
      question: "How can you align a form in horizontal layout in Bootstrap?",
      options1: ".form-horizontal",
      options2: ".form-group",
      options3: ".form-row",
      options4: ".form-inline",
      answer: 1,
    },
    {
      question: "Which class adds a blue background color in Bootstrap?",
      options1: ".bg-blue",
      options2: ".bg-primary",
      options3: ".bg-info",
      options4: ".bg-lightblue",
      answer: 2,
    },
  ],
  React: [
  {
    question: "Which hook is used for side effects in React?",
    options1: "useState",
    options2: "useEffect",
    options3: "useRef",
    options4: "useContext",
    answer: 2,
  },
  {
    question: "Which prop in React is used to pass data to a component?",
    options1: "state",
    options2: "props",
    options3: "data",
    options4: "value",
    answer: 2,
  },
  {
    question: "What is the purpose of the key prop in React lists?",
    options1: "To style list items",
    options2: "To uniquely identify elements",
    options3: "To sort the list",
    options4: "To filter list items",
    answer: 2,
  },
  {
    question: "What does lifting state up mean in React?",
    options1: "Sharing state between multiple components",
    options2: "Moving state to a lower component",
    options3: "Deleting component state",
    options4: "Resetting state values",
    answer: 1,
  },
  {
    question: "Which method is called after a component is updated in class components?",
    options1: "componentDidMount",
    options2: "componentDidUpdate",
    options3: "componentWillUnmount",
    options4: "render",
    answer: 2,
  },
  {
    question: "Which hook allows you to reference DOM elements directly?",
    options1: "useRef",
    options2: "useState",
    options3: "useEffect",
    options4: "useReducer",
    answer: 1,
  },
  {
    question: "What is the purpose of useReducer hook?",
    options1: "To replace useState",
    options2: "To manage complex state logic",
    options3: "To handle side effects",
    options4: "To access DOM elements",
    answer: 2,
  },
  {
    question: "Which of the following can be used for routing in React?",
    options1: "React Router",
    options2: "Redux",
    options3: "Axios",
    options4: "React Navigation",
    answer: 1,
  },
  {
    question: "How can you prevent a component from re-rendering in React?",
    options1: "Using React.memo",
    options2: "Using useEffect",
    options3: "Using useRef",
    options4: "Using useState",
    answer: 1,
  },
  {
    question: "What does the useContext hook do?",
    options1: "Manages side effects",
    options2: "Provides global state to components",
    options3: "Handles DOM events",
    options4: "Creates a new component",
    answer: 2,
  },
],
AI: [
  {
    question: "What does NLP stand for in AI?",
    options1: "Natural Learning Process",
    options2: "Natural Language Processing",
    options3: "Neural Logic Programming",
    options4: "Non Linear Processing",
    answer: 2,
  },
  {
    question: "Which type of machine learning uses labeled data?",
    options1: "Supervised Learning",
    options2: "Unsupervised Learning",
    options3: "Reinforcement Learning",
    options4: "Deep Learning",
    answer: 1,
  },
  {
    question: "Which algorithm is widely used for classification problems?",
    options1: "K-Means",
    options2: "Decision Tree",
    options3: "Apriori",
    options4: "PCA",
    answer: 2,
  },
  {
    question: "Which AI technique learns by interacting with the environment?",
    options1: "Supervised Learning",
    options2: "Unsupervised Learning",
    options3: "Reinforcement Learning",
    options4: "Clustering",
    answer: 3,
  },
  {
    question: "What is the main advantage of Deep Learning over traditional ML?",
    options1: "It works without any data",
    options2: "It can process raw and unstructured data",
    options3: "It uses less computation power",
    options4: "It avoids overfitting automatically",
    answer: 2,
  },
  {
    question: "Which neural network is best suited for image recognition?",
    options1: "CNN",
    options2: "RNN",
    options3: "ANN",
    options4: "GAN",
    answer: 1,
  },
  {
    question: "Which AI model is best for sequence-to-sequence tasks like translation?",
    options1: "Convolutional Neural Network",
    options2: "Recurrent Neural Network",
    options3: "Generative Adversarial Network",
    options4: "Perceptron",
    answer: 2,
  },
  {
    question: "Which library is widely used for deep learning in Python?",
    options1: "NumPy",
    options2: "Pandas",
    options3: "PyTorch",
    options4: "Matplotlib",
    answer: 3,
  },
  {
    question: "Which AI application detects objects in images?",
    options1: "Speech Recognition",
    options2: "Computer Vision",
    options3: "Expert System",
    options4: "Natural Language Processing",
    answer: 2,
  },
  {
    question: "Which AI technique powers recommendation systems like Netflix?",
    options1: "Reinforcement Learning",
    options2: "Collaborative Filtering",
    options3: "Decision Trees",
    options4: "Random Forest",
    answer: 2,
  },
],
ASP: [
  {
    question: "What does MVC stand for in ASP.NET?",
    options1: "Model View Controller",
    options2: "Main View Control",
    options3: "Model Variable Component",
    options4: "Module View Compiler",
    answer: 1,
  },
  {
    question: "Which directive is used to import namespaces in ASP.NET?",
    options1: "<%@ Import %>",
    options2: "<%@ Include %>",
    options3: "<%@ Namespace %>",
    options4: "<%@ Using %>",
    answer: 1,
  },
  {
    question: "In ASP.NET MVC, which folder contains view files?",
    options1: "Views",
    options2: "Controllers",
    options3: "Models",
    options4: "Scripts",
    answer: 1,
  },
  {
    question: "Which method in ASP.NET MVC is used to render a view?",
    options1: "return View()",
    options2: "return Page()",
    options3: "return HTML()",
    options4: "return Display()",
    answer: 1,
  },
  {
    question: "Which ASP.NET object is used to store data between requests?",
    options1: "Session",
    options2: "ViewBag",
    options3: "TempData",
    options4: "Cache",
    answer: 1,
  },
  {
    question: "Which lifecycle event is triggered first in ASP.NET Page Life Cycle?",
    options1: "Page_Init",
    options2: "Page_Load",
    options3: "Page_PreRender",
    options4: "Page_Unload",
    answer: 1,
  },
  {
    question: "What is Razor in ASP.NET?",
    options1: "A view engine for rendering HTML",
    options2: "A database engine",
    options3: "A routing library",
    options4: "A debugging tool",
    answer: 1,
  },
  {
    question: "Which symbol is used for Razor syntax in ASP.NET?",
    options1: "@",
    options2: "#",
    options3: "$",
    options4: "%",
    answer: 1,
  },
  {
    question: "Which HTTP method is used to submit forms in ASP.NET?",
    options1: "POST",
    options2: "GET",
    options3: "PUT",
    options4: "DELETE",
    answer: 1,
  },
  {
    question: "Which helper method is used to create HTML controls in Razor?",
    options1: "HtmlHelper",
    options2: "ControlHelper",
    options3: "UIHelper",
    options4: "FormHelper",
    answer: 1,
  },
],
Angular: [
  {
    question: "Which service in Angular is used for HTTP communication?",
    options1: "HttpClient",
    options2: "HttpModule",
    options3: "HttpService",
    options4: "FetchAPI",
    answer: 1,
  },
  {
    question: "What is the purpose of Angular Pipes?",
    options1: "Transform data before displaying it",
    options2: "Store data",
    options3: "Fetch API data",
    options4: "Validate forms",
    answer: 1,
  },
  {
    question: "Which lifecycle hook is called after a component is initialized?",
    options1: "ngOnInit()",
    options2: "ngAfterViewInit()",
    options3: "ngDoCheck()",
    options4: "ngOnChanges()",
    answer: 1,
  },
  {
    question: "Which Angular module is required for using forms?",
    options1: "FormsModule",
    options2: "HttpClientModule",
    options3: "ReactiveModule",
    options4: "BrowserModule",
    answer: 1,
  },
  {
    question: "What is two-way data binding syntax in Angular?",
    options1: "[()]",
    options2: "()[]",
    options3: "{}[]",
    options4: "<()>",
    answer: 1,
  },
  {
    question: "What does Angular Router do?",
    options1: "Handles navigation between views",
    options2: "Stores data",
    options3: "Applies styles",
    options4: "Validates forms",
    answer: 1,
  },
  {
    question: "Which command generates a new component in Angular?",
    options1: "ng generate component",
    options2: "ng create component",
    options3: "ng add component",
    options4: "npm install component",
    answer: 1,
  },
  {
    question: "What is the default change detection strategy in Angular?",
    options1: "CheckAlways",
    options2: "OnPush",
    options3: "Default",
    options4: "Observe",
    answer: 1,
  },
  {
    question: "What is the purpose of @Injectable decorator in Angular?",
    options1: "To make a class available for dependency injection",
    options2: "To create a component",
    options3: "To define a module",
    options4: "To create a directive",
    answer: 1,
  },
  {
    question: "Which directive is used for switch-case in Angular?",
    options1: "*ngSwitch",
    options2: "*ngCase",
    options3: "*ngIfElse",
    options4: "*ngChoice",
    answer: 1,
  },
],
DSA: [
  {
    question: "Which algorithm is used for minimum spanning tree?",
    options1: "Kruskal's Algorithm",
    options2: "DFS",
    options3: "BFS",
    options4: "Bellman-Ford",
    answer: 1,
  },
  {
    question: "What is the worst-case time complexity of Quick Sort?",
    options1: "O(n^2)",
    options2: "O(n log n)",
    options3: "O(log n)",
    options4: "O(n)",
    answer: 1,
  },
  {
    question: "Which data structure is used in BFS traversal?",
    options1: "Queue",
    options2: "Stack",
    options3: "Heap",
    options4: "Tree",
    answer: 1,
  },
  {
    question: "Which technique is used in Merge Sort?",
    options1: "Divide and Conquer",
    options2: "Dynamic Programming",
    options3: "Greedy Algorithm",
    options4: "Backtracking",
    answer: 1,
  },
  {
    question: "Which data structure allows insertion and deletion from both ends?",
    options1: "Deque",
    options2: "Stack",
    options3: "Queue",
    options4: "Priority Queue",
    answer: 1,
  },
  {
    question: "Which graph representation is more space-efficient for sparse graphs?",
    options1: "Adjacency List",
    options2: "Adjacency Matrix",
    options3: "Linked Matrix",
    options4: "Edge List",
    answer: 1,
  },
  {
    question: "Which algorithm is used in topological sorting?",
    options1: "DFS",
    options2: "BFS",
    options3: "Dijkstra",
    options4: "Kruskal",
    answer: 1,
  },
  {
    question: "What is the height of a complete binary tree with n nodes?",
    options1: "O(log n)",
    options2: "O(n)",
    options3: "O(n log n)",
    options4: "O(1)",
    answer: 1,
  },
  {
    question: "Which searching algorithm works on both directed and undirected graphs?",
    options1: "DFS and BFS",
    options2: "Dijkstra only",
    options3: "Prim's only",
    options4: "Binary Search",
    answer: 1,
  },
  {
    question: "Which algorithm is used for finding strongly connected components?",
    options1: "Kosaraju's Algorithm",
    options2: "Dijkstra's Algorithm",
    options3: "Prim's Algorithm",
    options4: "Bellman-Ford Algorithm",
    answer: 1,
  },
],
CyberSecurity: [
  {
    question: "Which protocol is used for secure file transfer?",
    options1: "SFTP",
    options2: "FTP",
    options3: "HTTP",
    options4: "SMTP",
    answer: 1,
  },
  {
    question: "Which type of attack involves injecting malicious SQL code?",
    options1: "SQL Injection",
    options2: "Phishing",
    options3: "Cross-Site Scripting",
    options4: "Brute Force",
    answer: 1,
  },
  {
    question: "What does 2FA stand for in cybersecurity?",
    options1: "Two-Factor Authentication",
    options2: "Two-File Access",
    options3: "Two-Factor Authorization",
    options4: "Two-Factor Agreement",
    answer: 1,
  },
  {
    question: "Which tool is commonly used for network packet analysis?",
    options1: "Wireshark",
    options2: "Photoshop",
    options3: "Notepad++",
    options4: "WinRAR",
    answer: 1,
  },
  {
    question: "Which security model focuses on data confidentiality?",
    options1: "Bell-LaPadula Model",
    options2: "Biba Model",
    options3: "Clark-Wilson Model",
    options4: "CIS Model",
    answer: 1,
  },
  {
    question: "Which type of malware disguises itself as legitimate software?",
    options1: "Trojan",
    options2: "Worm",
    options3: "Virus",
    options4: "Adware",
    answer: 1,
  },
  {
    question: "Which type of cyber attack targets DNS systems?",
    options1: "DNS Spoofing",
    options2: "SQL Injection",
    options3: "Cross-Site Request Forgery",
    options4: "Ransomware",
    answer: 1,
  },
  {
    question: "Which cryptographic algorithm is symmetric?",
    options1: "AES",
    options2: "RSA",
    options3: "ECC",
    options4: "Diffie-Hellman",
    answer: 1,
  },
  {
    question: "Which vulnerability allows attackers to run scripts in another user’s browser?",
    options1: "Cross-Site Scripting (XSS)",
    options2: "SQL Injection",
    options3: "Phishing",
    options4: "Brute Force",
    answer: 1,
  },
  {
    question: "What is the main function of IDS (Intrusion Detection System)?",
    options1: "To detect unauthorized access",
    options2: "To block malware",
    options3: "To manage passwords",
    options4: "To encrypt data",
    answer: 1,
  },
],
DataScience: [
  {
    question: "Which algorithm is commonly used for classification?",
    options1: "Decision Tree",
    options2: "K-Means",
    options3: "Apriori",
    options4: "PCA",
    answer: 1,
  },
  {
    question: "What does 'ETL' stand for in data processing?",
    options1: "Extract, Transform, Load",
    options2: "Enter, Test, Learn",
    options3: "Evaluate, Train, Loop",
    options4: "Encode, Transfer, Load",
    answer: 1,
  },
  {
    question: "Which Python library is used for machine learning?",
    options1: "Scikit-learn",
    options2: "Flask",
    options3: "Pandas",
    options4: "Matplotlib",
    answer: 1,
  },
  {
    question: "Which metric measures the accuracy of a regression model?",
    options1: "R-squared",
    options2: "Precision",
    options3: "Recall",
    options4: "F1-score",
    answer: 1,
  },
  {
    question: "Which technique reduces the number of variables in a dataset?",
    options1: "Dimensionality Reduction",
    options2: "Data Cleaning",
    options3: "Feature Engineering",
    options4: "Data Normalization",
    answer: 1,
  },
  {
    question: "What type of chart is best for time-series data?",
    options1: "Line Chart",
    options2: "Pie Chart",
    options3: "Bar Chart",
    options4: "Scatter Plot",
    answer: 1,
  },
  {
    question: "Which concept describes a model performing well on training data but poorly on test data?",
    options1: "Overfitting",
    options2: "Underfitting",
    options3: "Bias",
    options4: "Variance",
    answer: 1,
  },
  {
    question: "Which SQL command is used to extract data from a database?",
    options1: "SELECT",
    options2: "INSERT",
    options3: "UPDATE",
    options4: "DELETE",
    answer: 1,
  },
  {
    question: "Which method splits data into training and testing sets?",
    options1: "train_test_split",
    options2: "split_data",
    options3: "divide_dataset",
    options4: "data_split",
    answer: 1,
  },
  {
    question: "Which library is used for deep learning in Python?",
    options1: "TensorFlow",
    options2: "Matplotlib",
    options3: "Scikit-learn",
    options4: "Requests",
    answer: 1,
  },
],




};

export default data2;
